// source: movie.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var actor_pb = require('./actor_pb.js');
goog.object.extend(proto, actor_pb);
goog.exportSymbol('proto.artemis.Movie', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.artemis.Movie = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.artemis.Movie.repeatedFields_, null);
};
goog.inherits(proto.artemis.Movie, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.artemis.Movie.displayName = 'proto.artemis.Movie';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.artemis.Movie.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.artemis.Movie.prototype.toObject = function(opt_includeInstance) {
  return proto.artemis.Movie.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.artemis.Movie} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.artemis.Movie.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    actorsList: jspb.Message.toObjectList(msg.getActorsList(),
    actor_pb.Actor.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.artemis.Movie}
 */
proto.artemis.Movie.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.artemis.Movie;
  return proto.artemis.Movie.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.artemis.Movie} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.artemis.Movie}
 */
proto.artemis.Movie.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new actor_pb.Actor;
      reader.readMessage(value,actor_pb.Actor.deserializeBinaryFromReader);
      msg.addActors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.artemis.Movie.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.artemis.Movie.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.artemis.Movie} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.artemis.Movie.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getActorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      actor_pb.Actor.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.artemis.Movie.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.artemis.Movie} returns this
 */
proto.artemis.Movie.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Actor actors = 2;
 * @return {!Array<!proto.artemis.Actor>}
 */
proto.artemis.Movie.prototype.getActorsList = function() {
  return /** @type{!Array<!proto.artemis.Actor>} */ (
    jspb.Message.getRepeatedWrapperField(this, actor_pb.Actor, 2));
};


/**
 * @param {!Array<!proto.artemis.Actor>} value
 * @return {!proto.artemis.Movie} returns this
*/
proto.artemis.Movie.prototype.setActorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.artemis.Actor=} opt_value
 * @param {number=} opt_index
 * @return {!proto.artemis.Actor}
 */
proto.artemis.Movie.prototype.addActors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.artemis.Actor, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.artemis.Movie} returns this
 */
proto.artemis.Movie.prototype.clearActorsList = function() {
  return this.setActorsList([]);
};


goog.object.extend(exports, proto.artemis);
